// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mlb/shared.proto

package mlb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 构建状态
type BuildStatus int32

const (
	BuildStatus_PENDING    BuildStatus = 0
	BuildStatus_INPROGRESS BuildStatus = 1
	BuildStatus_SUCCESS    BuildStatus = 2
	BuildStatus_FAILED     BuildStatus = 3
	BuildStatus_CANCELED   BuildStatus = 4
)

var BuildStatus_name = map[int32]string{
	0: "PENDING",
	1: "INPROGRESS",
	2: "SUCCESS",
	3: "FAILED",
	4: "CANCELED",
}

var BuildStatus_value = map[string]int32{
	"PENDING":    0,
	"INPROGRESS": 1,
	"SUCCESS":    2,
	"FAILED":     3,
	"CANCELED":   4,
}

func (x BuildStatus) String() string {
	return proto.EnumName(BuildStatus_name, int32(x))
}

func (BuildStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c46991e1197981a7, []int{0}
}

// 响应状态
type Status struct {
	// 状态码，0代表正常
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 信息, 状态码等于0时为空
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_c46991e1197981a7, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 任务实体
type TaskEntity struct {
	// 唯一标识码
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// 创建时间
	CreatedAt int64 `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// 更新时间
	UpdatedAt int64 `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	// 构建状态
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 处理器
	Handler string `protobuf:"bytes,5,opt,name=handler,proto3" json:"handler,omitempty"`
	// 元数据
	Meta string `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	// 日志
	Log                  string   `protobuf:"bytes,7,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskEntity) Reset()         { *m = TaskEntity{} }
func (m *TaskEntity) String() string { return proto.CompactTextString(m) }
func (*TaskEntity) ProtoMessage()    {}
func (*TaskEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_c46991e1197981a7, []int{1}
}

func (m *TaskEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskEntity.Unmarshal(m, b)
}
func (m *TaskEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskEntity.Marshal(b, m, deterministic)
}
func (m *TaskEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskEntity.Merge(m, src)
}
func (m *TaskEntity) XXX_Size() int {
	return xxx_messageInfo_TaskEntity.Size(m)
}
func (m *TaskEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskEntity.DiscardUnknown(m)
}

var xxx_messageInfo_TaskEntity proto.InternalMessageInfo

func (m *TaskEntity) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TaskEntity) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *TaskEntity) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *TaskEntity) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TaskEntity) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func (m *TaskEntity) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *TaskEntity) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func init() {
	proto.RegisterEnum("mlb.BuildStatus", BuildStatus_name, BuildStatus_value)
	proto.RegisterType((*Status)(nil), "mlb.Status")
	proto.RegisterType((*TaskEntity)(nil), "mlb.TaskEntity")
}

func init() {
	proto.RegisterFile("proto/mlb/shared.proto", fileDescriptor_c46991e1197981a7)
}

var fileDescriptor_c46991e1197981a7 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x41, 0x4f, 0x83, 0x30,
	0x18, 0x86, 0x65, 0x30, 0x90, 0x6f, 0xc6, 0x90, 0xef, 0xb0, 0xf4, 0xe0, 0x61, 0xd9, 0x69, 0xf1,
	0xe0, 0x0e, 0x26, 0xde, 0x91, 0xe1, 0x42, 0x62, 0x70, 0x16, 0xfd, 0x01, 0x65, 0x6d, 0x36, 0x62,
	0x19, 0x0b, 0x6d, 0x0f, 0xfe, 0x2f, 0x7f, 0xa0, 0x69, 0x41, 0x77, 0x7b, 0x9f, 0xf7, 0xcd, 0x97,
	0x3c, 0x2d, 0xcc, 0xcf, 0x7d, 0xa7, 0xbb, 0x75, 0x2b, 0xeb, 0xb5, 0x3a, 0xb2, 0x5e, 0xf0, 0x07,
	0x57, 0xa0, 0xdf, 0xca, 0x7a, 0xf9, 0x04, 0x61, 0xa5, 0x99, 0x36, 0x0a, 0x11, 0x82, 0x7d, 0xc7,
	0x05, 0xf1, 0x16, 0xde, 0x6a, 0x4a, 0x5d, 0x46, 0x02, 0x51, 0x2b, 0x94, 0x62, 0x07, 0x41, 0x26,
	0x0b, 0x6f, 0x15, 0xd3, 0x3f, 0x5c, 0xfe, 0x78, 0x00, 0x1f, 0x4c, 0x7d, 0xe5, 0x27, 0xdd, 0xe8,
	0x6f, 0x7b, 0x6c, 0x4c, 0xc3, 0xdd, 0x71, 0x4c, 0x5d, 0xc6, 0x3b, 0x88, 0xf7, 0xbd, 0x60, 0x5a,
	0xf0, 0x54, 0xbb, 0x73, 0x9f, 0x5e, 0x0a, 0xbb, 0x9a, 0x33, 0x1f, 0x57, 0x7f, 0x58, 0xff, 0x0b,
	0x9c, 0x43, 0xa8, 0x9c, 0x16, 0x09, 0x9c, 0xce, 0x48, 0x56, 0xe8, 0xc8, 0x4e, 0x5c, 0x8a, 0x9e,
	0x4c, 0x07, 0xa1, 0x11, 0xad, 0x41, 0x2b, 0x34, 0x23, 0xe1, 0x60, 0x60, 0x33, 0x26, 0xe0, 0xcb,
	0xee, 0x40, 0x22, 0x57, 0xd9, 0x78, 0xff, 0x0e, 0xb3, 0x67, 0xd3, 0x48, 0x3e, 0xbe, 0x79, 0x06,
	0xd1, 0x2e, 0x2f, 0x37, 0x45, 0xb9, 0x4d, 0xae, 0xf0, 0x16, 0xa0, 0x28, 0x77, 0xf4, 0x6d, 0x4b,
	0xf3, 0xaa, 0x4a, 0x3c, 0x3b, 0x56, 0x9f, 0x59, 0x66, 0x61, 0x82, 0x00, 0xe1, 0x4b, 0x5a, 0xbc,
	0xe6, 0x9b, 0xc4, 0xc7, 0x1b, 0xb8, 0xce, 0xd2, 0x32, 0xcb, 0x2d, 0x05, 0x75, 0xe8, 0x7e, 0xf3,
	0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xd3, 0x04, 0x01, 0x67, 0x01, 0x00, 0x00,
}
