// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mlb/task.proto

package mlb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 构建状态
type BuildStatus int32

const (
	BuildStatus_PENDING    BuildStatus = 0
	BuildStatus_PROCESSING BuildStatus = 1
	BuildStatus_SUCCESS    BuildStatus = 2
	BuildStatus_FAILED     BuildStatus = 3
	BuildStatus_CANCELED   BuildStatus = 4
)

var BuildStatus_name = map[int32]string{
	0: "PENDING",
	1: "PROCESSING",
	2: "SUCCESS",
	3: "FAILED",
	4: "CANCELED",
}

var BuildStatus_value = map[string]int32{
	"PENDING":    0,
	"PROCESSING": 1,
	"SUCCESS":    2,
	"FAILED":     3,
	"CANCELED":   4,
}

func (x BuildStatus) String() string {
	return proto.EnumName(BuildStatus_name, int32(x))
}

func (BuildStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ff78b02eed61a09d, []int{0}
}

// 查询请求
type QueryRequest struct {
	// 任务ID
	TaskID               string   `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff78b02eed61a09d, []int{0}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

// 查询回复
type QueryResponse struct {
	// 状态
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 构建状态
	BuildStatus BuildStatus `protobuf:"varint,2,opt,name=buildStatus,proto3,enum=mlb.BuildStatus" json:"buildStatus,omitempty"`
	// 视频的存放地址，仅当构建成功时有值
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// 任务创建时间
	CreatedAt int64 `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// 任务更新时间
	UpdatedAt            int64    `protobuf:"varint,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff78b02eed61a09d, []int{1}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *QueryResponse) GetBuildStatus() BuildStatus {
	if m != nil {
		return m.BuildStatus
	}
	return BuildStatus_PENDING
}

func (m *QueryResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *QueryResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *QueryResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// 取消请求
type CancelRequest struct {
	// 任务ID
	TaskID               string   `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelRequest) Reset()         { *m = CancelRequest{} }
func (m *CancelRequest) String() string { return proto.CompactTextString(m) }
func (*CancelRequest) ProtoMessage()    {}
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff78b02eed61a09d, []int{2}
}

func (m *CancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRequest.Unmarshal(m, b)
}
func (m *CancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRequest.Marshal(b, m, deterministic)
}
func (m *CancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRequest.Merge(m, src)
}
func (m *CancelRequest) XXX_Size() int {
	return xxx_messageInfo_CancelRequest.Size(m)
}
func (m *CancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRequest proto.InternalMessageInfo

func (m *CancelRequest) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

// 取消回复
type CancelResponse struct {
	// 状态
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelResponse) Reset()         { *m = CancelResponse{} }
func (m *CancelResponse) String() string { return proto.CompactTextString(m) }
func (*CancelResponse) ProtoMessage()    {}
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff78b02eed61a09d, []int{3}
}

func (m *CancelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelResponse.Unmarshal(m, b)
}
func (m *CancelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelResponse.Marshal(b, m, deterministic)
}
func (m *CancelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelResponse.Merge(m, src)
}
func (m *CancelResponse) XXX_Size() int {
	return xxx_messageInfo_CancelResponse.Size(m)
}
func (m *CancelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelResponse proto.InternalMessageInfo

func (m *CancelResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("mlb.BuildStatus", BuildStatus_name, BuildStatus_value)
	proto.RegisterType((*QueryRequest)(nil), "mlb.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "mlb.QueryResponse")
	proto.RegisterType((*CancelRequest)(nil), "mlb.CancelRequest")
	proto.RegisterType((*CancelResponse)(nil), "mlb.CancelResponse")
}

func init() {
	proto.RegisterFile("proto/mlb/task.proto", fileDescriptor_ff78b02eed61a09d)
}

var fileDescriptor_ff78b02eed61a09d = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0x29, 0xe5, 0xef, 0x2f, 0xb7, 0x40, 0xea, 0xd5, 0x90, 0x86, 0xb8, 0x20, 0x35, 0x51,
	0xe2, 0x02, 0x4c, 0x89, 0x0f, 0x80, 0xa5, 0x1a, 0x12, 0x83, 0xd0, 0xea, 0x03, 0xb4, 0x74, 0x12,
	0x0d, 0x53, 0xc0, 0xce, 0xcc, 0xc2, 0x17, 0xf3, 0xf9, 0xcc, 0xcc, 0x14, 0x29, 0x2b, 0xe3, 0xae,
	0xe7, 0x7c, 0xe7, 0xe6, 0xf6, 0xcc, 0x0c, 0x9c, 0xef, 0x8a, 0x2d, 0xdf, 0x8e, 0x72, 0x9a, 0x8e,
	0x78, 0xc2, 0xd6, 0x43, 0x25, 0xd1, 0xcc, 0x69, 0xda, 0xeb, 0x1e, 0x10, 0x7b, 0x4b, 0x0a, 0x92,
	0x69, 0xe8, 0x5d, 0x41, 0x6b, 0x29, 0x48, 0xf1, 0x19, 0x91, 0x0f, 0x41, 0x18, 0xc7, 0x2e, 0x58,
	0x72, 0x74, 0x36, 0x75, 0x8d, 0xbe, 0x31, 0x68, 0x46, 0xa5, 0xf2, 0xbe, 0x0c, 0x68, 0x97, 0x41,
	0xb6, 0xdb, 0x6e, 0x18, 0xc1, 0x4b, 0xb0, 0x18, 0x4f, 0xb8, 0x60, 0x2a, 0x69, 0xfb, 0xf6, 0x30,
	0xa7, 0xe9, 0x30, 0x56, 0x56, 0x54, 0x22, 0xf4, 0xc1, 0x4e, 0xc5, 0x3b, 0xcd, 0xb4, 0xed, 0xd6,
	0xfb, 0xc6, 0xa0, 0xe3, 0x3b, 0x2a, 0x79, 0x7f, 0xf0, 0xa3, 0x6a, 0x08, 0x1d, 0x30, 0x45, 0x41,
	0x5d, 0x53, 0xed, 0x97, 0x9f, 0x78, 0x01, 0xcd, 0x55, 0x41, 0x12, 0x4e, 0xb2, 0x09, 0x77, 0xa1,
	0x6f, 0x0c, 0xcc, 0xe8, 0x60, 0x48, 0x2a, 0x76, 0x59, 0x49, 0x6d, 0x4d, 0x7f, 0x0c, 0xef, 0x1a,
	0xda, 0x41, 0xb2, 0x59, 0x11, 0xfa, 0x5b, 0xc3, 0x3b, 0xe8, 0xec, 0x83, 0x7f, 0x68, 0x78, 0xb3,
	0x04, 0xbb, 0xd2, 0x04, 0x6d, 0xf8, 0xbf, 0x08, 0xe7, 0xd3, 0xd9, 0xfc, 0xd1, 0xa9, 0x61, 0x07,
	0x60, 0x11, 0x3d, 0x07, 0x61, 0x1c, 0x4b, 0x6d, 0x48, 0x18, 0xbf, 0x06, 0x52, 0x3b, 0x75, 0x04,
	0xb0, 0x1e, 0x26, 0xb3, 0xa7, 0x70, 0xea, 0x98, 0xd8, 0x82, 0x93, 0x60, 0x32, 0x0f, 0x42, 0xa9,
	0x1a, 0x7e, 0x0e, 0x8d, 0x97, 0x84, 0xad, 0xf1, 0x16, 0xfe, 0xa9, 0x23, 0xc7, 0x53, 0xb5, 0xb8,
	0x7a, 0x4f, 0x3d, 0xac, 0x5a, 0xfa, 0x7f, 0xbd, 0x1a, 0x8e, 0xc1, 0xd2, 0x1d, 0x50, 0xf3, 0xa3,
	0xe6, 0xbd, 0xb3, 0x23, 0x6f, 0x3f, 0x94, 0x5a, 0xea, 0x25, 0x8c, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x2e, 0xad, 0x66, 0x2f, 0x3e, 0x02, 0x00, 0x00,
}
