// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mlb/video.proto

package mlb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 构建回复
type BuildResponse struct {
	// 状态
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 任务ID
	TaskID               string   `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86c0ddff4cbb1f41, []int{0}
}

func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (m *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(m, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BuildResponse) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

// 笔记页
type Page struct {
	// 页码
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// 笔迹
	Handwriting          []byte   `protobuf:"bytes,2,opt,name=handwriting,proto3" json:"handwriting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_86c0ddff4cbb1f41, []int{1}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Page) GetHandwriting() []byte {
	if m != nil {
		return m.Handwriting
	}
	return nil
}

// 构建请求
type BuildRequest struct {
	// 笔记页内容
	Page []*Page `protobuf:"bytes,1,rep,name=page,proto3" json:"page,omitempty"`
	// 音频文件地址, 以http://或https://开始
	Audio string `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
	// 视频开始的时间戳，单位毫秒
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 合成视频的长度，单位毫秒
	Duration             int64    `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86c0ddff4cbb1f41, []int{2}
}

func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (m *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(m, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetPage() []*Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *BuildRequest) GetAudio() string {
	if m != nil {
		return m.Audio
	}
	return ""
}

func (m *BuildRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BuildRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterType((*BuildResponse)(nil), "mlb.BuildResponse")
	proto.RegisterType((*Page)(nil), "mlb.Page")
	proto.RegisterType((*BuildRequest)(nil), "mlb.BuildRequest")
}

func init() {
	proto.RegisterFile("proto/mlb/video.proto", fileDescriptor_86c0ddff4cbb1f41)
}

var fileDescriptor_86c0ddff4cbb1f41 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4b, 0x85, 0x40,
	0x14, 0x85, 0x33, 0x7f, 0x90, 0xd7, 0xd7, 0xa2, 0x4b, 0x3d, 0x44, 0x0a, 0xc4, 0x36, 0xae, 0x7c,
	0x61, 0xab, 0x36, 0x2d, 0xa2, 0x4d, 0xd0, 0x22, 0x26, 0x68, 0x3f, 0x32, 0x83, 0x6f, 0x48, 0x1d,
	0x73, 0xc6, 0x6a, 0xd3, 0xff, 0x1e, 0x5e, 0xe5, 0x3d, 0x97, 0xe7, 0x3b, 0xcc, 0xdc, 0x8f, 0x03,
	0x57, 0xfd, 0xa0, 0xad, 0xde, 0xb5, 0x4d, 0xb5, 0xfb, 0x56, 0x42, 0xea, 0x82, 0x32, 0xba, 0x6d,
	0x53, 0x25, 0xdb, 0x63, 0x67, 0xf6, 0x7c, 0x90, 0x62, 0x2e, 0xb3, 0x57, 0x38, 0x7f, 0x1a, 0x55,
	0x23, 0x98, 0x34, 0xbd, 0xee, 0x8c, 0xc4, 0x5b, 0x08, 0x8c, 0xe5, 0x76, 0x34, 0xb1, 0x93, 0x3a,
	0x79, 0x54, 0x46, 0x45, 0xdb, 0x54, 0xc5, 0x3b, 0x21, 0xb6, 0x54, 0xb8, 0x85, 0xc0, 0x72, 0xf3,
	0xf9, 0xf2, 0x1c, 0x9f, 0xa6, 0x4e, 0x1e, 0xb2, 0x25, 0x65, 0x8f, 0xe0, 0xbd, 0xf1, 0x5a, 0xe2,
	0x25, 0xf8, 0xaa, 0x13, 0xf2, 0x97, 0xfe, 0xf0, 0xd9, 0x1c, 0x30, 0x85, 0x68, 0xcf, 0x3b, 0xf1,
	0x33, 0x28, 0xab, 0xba, 0x9a, 0x9e, 0x6e, 0xd8, 0x1a, 0x65, 0x7f, 0xb0, 0x59, 0x6c, 0xbe, 0x46,
	0x69, 0x2c, 0xde, 0x80, 0xd7, 0xf3, 0x5a, 0xc6, 0x4e, 0xea, 0xe6, 0x51, 0x19, 0x92, 0xca, 0x74,
	0x80, 0x11, 0x9e, 0xce, 0xf0, 0x51, 0x28, 0xbd, 0x58, 0xcc, 0x01, 0xaf, 0x21, 0xb4, 0xaa, 0x95,
	0xc6, 0xf2, 0xb6, 0x8f, 0xdd, 0xd4, 0xc9, 0x5d, 0x76, 0x04, 0x98, 0xc0, 0x99, 0x18, 0x07, 0x6e,
	0x95, 0xee, 0x62, 0x8f, 0xca, 0x43, 0x2e, 0x1f, 0xc0, 0xff, 0x98, 0x86, 0xc3, 0x3b, 0xf0, 0xc9,
	0x03, 0x2f, 0xe8, 0xe4, 0xda, 0x29, 0xc1, 0x35, 0x9a, 0x47, 0xcb, 0x4e, 0xaa, 0x80, 0xe6, 0xbc,
	0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xee, 0x72, 0x97, 0x84, 0x01, 0x00, 0x00,
}
